Add allure

diff --git a/.github/workflows/allure-report.yml b/.github/workflows/allure-report.yml
--- a/.github/workflows/allure-report.yml
+++ b/.github/workflows/allure-report.yml
@@ -51,9 +51,12 @@ jobs:
             sleep 5
           done
 
-      - name: Run tests and generate report
+      - name: Run tests
         run: |
-          pytest --alluredir=allure-results
+          pytest --alluredir=allure-results || echo "Some tests failed"
+
+      - name: Generate Allure report
+        run: |
           allure generate allure-results -o allure-report --clean
 
       - name: Deploy to GitHub Pages
